"""
app.py
------
The Streamlit UI for PolicyLens. This file is intentionally "thin" -- it
handles file uploads, session state, and layout, and delegates all the real
work to the src/ modules:

    pdf_processor.py   -> extract + chunk PDF text
    embeddings.py       -> turn text into vectors
    retriever.py        -> FAISS-based similarity search
    llm.py               -> grounded Q&A + change classification (OpenAI calls)
    policy_analyzer.py  -> orchestrates the Q&A pipeline + Python calculator
    comparison.py        -> orchestrates the policy-diff pipeline

Run with:  streamlit run app.py
"""

import tempfile

import streamlit as st
from dotenv import load_dotenv

from src.policy_analyzer import build_policy_index, answer_policy_question
from src.comparison import compare_policies
from src.llm import check_ollama_ready

load_dotenv()  # reads optional settings (e.g. OLLAMA_MODEL) from .env into the environment

st.set_page_config(page_title="PolicyLens", page_icon="📄", layout="wide")


def save_upload_to_temp(uploaded_file) -> str:
    """Streamlit gives us an in-memory file object; write it to disk so
    PyMuPDF (which expects a file path) can open it."""
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp.write(uploaded_file.getvalue())
        return tmp.name


def render_evidence(chunks: list[dict]):
    """Show each retrieved chunk as a labeled, expandable source excerpt."""
    if not chunks:
        st.info("No supporting excerpts were retrieved.")
        return
    for i, chunk in enumerate(chunks, start=1):
        with st.expander(
            f"Excerpt {i} — Page {chunk.get('page', '?')} — "
            f"{chunk.get('section', 'General')} "
            f"(similarity: {chunk.get('score', 0):.2f})"
        ):
            st.write(chunk["text"])


def render_calculation(calc: dict | None):
    """Render the Python-computed numbers, clearly separated from the LLM's text."""
    if not calc:
        return

    st.markdown("#### 🧮 Calculated (Python, not the LLM)")

    if calc.get("type") == "attendance":
        st.write(f"- Current attendance: **{calc['attended']}/{calc['total_so_far']}** "
                  f"= **{calc['current_percent']}%**")
        st.write(f"- Policy requires: **{calc['required_percent']}%**")
        st.write("- Currently meets requirement: "
                  f"{'✅ Yes' if calc['currently_meets_requirement'] else '❌ No'}")
        if "projected_percent" in calc:
            st.write(f"- If you miss **{calc['classes_missed_more']}** more classes "
                      f"(out of {calc['projected_total']} total): "
                      f"projected attendance = **{calc['projected_percent']}%**")
            st.write("- Would still meet requirement: "
                      f"{'✅ Yes' if calc['would_meet_requirement'] else '❌ No'}")
            st.write(f"- Max additional classes you can miss and stay compliant: "
                      f"**{calc['max_additional_classes_can_miss']}**")

    elif calc.get("type") == "cgpa":
        st.write(f"- Your CGPA: **{calc['user_cgpa']}**")
        st.write(f"- Required CGPA: **{calc['required_cgpa']}**")
        st.write(f"- Eligible: {'✅ Yes' if calc['is_eligible'] else '❌ No'}")

    st.caption(
        "These numbers were computed directly in Python from figures found in "
        "the policy text and your question — not generated by the LLM."
    )


# --- Session state setup -----------------------------------------------
# We cache the vector store per uploaded file so re-asking a question
# doesn't re-embed the whole document every time.
if "vector_store" not in st.session_state:
    st.session_state.vector_store = None
if "indexed_filename" not in st.session_state:
    st.session_state.indexed_filename = None


# --- Page header ----------------------------------------------------------
st.title("📄 PolicyLens")
st.caption("AI Policy Impact Analyzer — upload a policy PDF, ask how it applies to you.")

# PolicyLens runs entirely locally (Sentence-Transformers + Ollama), so
# there's no API key to check -- but we do check that Ollama itself is
# running and that the model we need has been pulled, since those are the
# most common setup mistakes for a first run.
ollama_ready, ollama_message = check_ollama_ready()
if not ollama_ready:
    st.error(ollama_message)
    st.stop()

tab_qa, tab_compare = st.tabs(["🔍 Policy Q&A", "🔁 Policy Comparison"])


# ============================================================================
# TAB 1: Policy Q&A
# ============================================================================
with tab_qa:
    st.subheader("1. Upload a policy document")
    uploaded_pdf = st.file_uploader("Upload policy PDF", type=["pdf"], key="qa_pdf")

    if uploaded_pdf is not None:
        # Only rebuild the index if this is a new/different file.
        if st.session_state.indexed_filename != uploaded_pdf.name:
            with st.spinner("Reading and indexing the document..."):
                pdf_path = save_upload_to_temp(uploaded_pdf)
                st.session_state.vector_store = build_policy_index(pdf_path)
                st.session_state.indexed_filename = uploaded_pdf.name
            st.success(f"Indexed '{uploaded_pdf.name}' "
                       f"({len(st.session_state.vector_store.chunks)} chunks).")

    st.subheader("2. Ask a question")
    question = st.text_input(
        "e.g. \"I have attended 32 out of 45 classes. What happens if I miss 3 more?\""
    )
    analyze_clicked = st.button("Analyze Policy", type="primary")

    if analyze_clicked:
        if st.session_state.vector_store is None:
            st.warning("Please upload a policy PDF first.")
        elif not question.strip():
            st.warning("Please enter a question.")
        else:
            with st.spinner("Retrieving relevant policy sections and generating an answer..."):
                result = answer_policy_question(st.session_state.vector_store, question)

            st.subheader("Answer")
            st.write(result["answer"])

            render_calculation(result["calculation"])

            st.subheader("📚 Policy Evidence")
            st.caption(
                "The excerpts below are what the answer above was grounded in. "
                "Anything not shown here was not used to generate the answer."
            )
            render_evidence(result["evidence"])


# ============================================================================
# TAB 2: Policy Comparison
# ============================================================================
with tab_compare:
    st.subheader("Compare two versions of a policy")
    col1, col2 = st.columns(2)
    with col1:
        old_pdf = st.file_uploader("Older version", type=["pdf"], key="old_pdf")
    with col2:
        new_pdf = st.file_uploader("Newer version", type=["pdf"], key="new_pdf")

    if st.button("Compare Policies"):
        if not old_pdf or not new_pdf:
            st.warning("Please upload both versions.")
        else:
            with st.spinner("Comparing documents... this may take a moment."):
                old_path = save_upload_to_temp(old_pdf)
                new_path = save_upload_to_temp(new_pdf)
                changes = compare_policies(old_path, new_path)

            if not changes:
                st.info("No meaningful differences were detected between the two documents.")
            else:
                st.success(f"Found {len(changes)} change(s).")
                type_icons = {"Added": "🟢", "Removed": "🔴", "Modified": "🟡"}
                for change in changes:
                    icon = type_icons.get(change["change_type"], "⚪")
                    with st.expander(f"{icon} {change['change_type']}: {change['summary']}"):
                        st.markdown(f"**Who is affected:** {change['who_is_affected']}")
                        c1, c2 = st.columns(2)
                        with c1:
                            st.markdown("**Old text**")
                            st.write(change["old_text"] or "_(not present)_")
                        with c2:
                            st.markdown("**New text**")
                            st.write(change["new_text"] or "_(not present)_")
